spring:
#  datasource:
#    url: jdbc:mysql://
#    username:
#    password:
#    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /console
  devtools:
    livereload:
      enabled: true
  thymeleaf:
      cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 705550150202-efmj9jc3h7vd0ddkgbhtf8g3svs20201.apps.googleusercontent.com
            client-secret: 5YWt9_CQweeHpS1m3t1s9tZ4
          facebook:
            client-id: 711527002566365
            client-secret: a3b692831bc1e5d0535ada73d50c3986
custom:
  oauth2:
    kakao:
      client-id: 328065d5cbaad4dccdc9794601b4c0fd